// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/lib')['ElButton']
    ElCard: typeof import('element-plus/lib')['ElCard']
    ElCol: typeof import('element-plus/lib')['ElCol']
    ElForm: typeof import('element-plus/lib')['ElForm']
    ElFormItem: typeof import('element-plus/lib')['ElFormItem']
    ElImage: typeof import('element-plus/lib')['ElImage']
    ElInput: typeof import('element-plus/lib')['ElInput']
    ElMenu: typeof import('element-plus/lib')['ElMenu']
    ElMenuItem: typeof import('element-plus/lib')['ElMenuItem']
    ElRow: typeof import('element-plus/lib')['ElRow']
    ElSubMenu: typeof import('element-plus/lib')['ElSubMenu']
  }
}

export { }
